### ISSUE TITLE
Korrektur des Projekts

### ISSUE THREAD

**Issue by chede100** [ProPra16/programmierpraktikum-abschlussprojekt-pwnyhof#9]
Falls das Programm nur schwer auszuführen ist, kann ich in github auch nen Ordner mit ner runnable jar hochladen.

**Comment by yyazgan** [comment]
Das ist erstmal nicht nötig. Falls nötig, so werde ich euch Bescheid geben.

**Comment by bendisposto** [comment]
- Building per Travis funktioniert nicht, test schlagen fehl
- Gepackte Version funktioniert nicht, weil die location der fxml Files nicht korrekt ist

**Comment by chede100** [comment]
Building per Travis habe ich gerade korrigiert. Anscheinend wurde von jemanden ein falscher Test geschrieben.

**Comment by yyazgan** [comment]
Über Eclipse funktioniert alles ohne Probleme, jedoch nicht über die Konsole:

`Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Location is required.
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3207)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
        at de.hhu.propra16.tddt.TDDTStart.start(TDDTStart.java:22)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application de.hhu.propra16.tddt.TDDTStart
`

**Comment by chede100** [comment]
Habe einen Ordner mit einer runable .jar hochgeladen (für Windows).
Gegebenenfalls muss noch der Pfad zur java.exe in der start.bat angepasst werden.

**Comment by yyazgan** [comment]
Das ist nicht ausreichend. Es sollte auf der Kommandozeile kompilierbar sein.

**Comment by bendisposto** [comment]
Mein Tipp: Findet heraus, wo die Resourcen-Dateien (wie zum Beispiel .fxml)  liegen müssen. 
Das ist das Problem, wenn man nur mit einer IDE arbeitet.

**Comment by bendisposto** [comment]
Das hier ist auch komisch: 
processCompile = Runtime.getRuntime().exec("javac " + codeFilePath);

**Comment by chede100** [comment]
Haben das gemacht um eine .class erstellen zu können, damit der User diese ausführen kann.
Per:
processRun = Runtime.getRuntime().exec("java -cp " + info.getPathToFiles() + " " + info.getCodeFileName() + args)
Haben das anders leider nicht hinbekommen.

**Comment by chede100** [comment]
Der User kann dadurch also auf den run-Button drücken um das Programm zu starten.
(und natürlich Argumente übergeben)

**Comment by bendisposto** [comment]
Mir ist nicht ganz klar, warum. Die Kata Bibliothek compiliert doch die Java Strings und lässt die Tests laufen. 

Oder ist das ein Zusatz feature? Fall ja, werden die Dateien nachher auch aufgeräumt?

**Comment by chede100** [comment]
Das ist ein Zusatz feature. Wollten noch, dass der User sein Programm von unserer "mini IDE" aus starten kann. Die .class Dateien werden in der Hinsicht nicht aufgeräumt bzw. gelöscht. Man kann das Programm dadurch halt aus dem Ordner Task/AufgabenName/ nehmen und außerhalb des TDDTrainers ausführen, falls man dies möchte.
Hoffe die Idee habe ich verständlich beschrieben :)

**Comment by chede100** [comment]
Aber ich verstehe wo das Problem ist. Wenn eine zweite Person die gleiche Aufgabe bearbeiten will, kann diese nur am Speicherstand der vorherigen Person weiterarbeiten. Dieses Problem haben wir aus Zeitmangel nicht beheben können.

Eine Idee wäre ja z.B., dass man ein Backup-Ordner hat aus dem, wenn man Auf File->New klickt der Anfangsstand geladen wird und der aktuelle Ordner Task/AufgabenName überschrieben/gelöscht wird.

**Comment by chede100** [comment]
Also die .jar ist jetzt unter linux und windows ausführbar.
Hoffe, dass dies die Bedingung erfüllt.
Dazu muss nur gegebenenfalls die .bat oder .sh angepasst werden.

**Comment by yyazgan** [comment]
Euer Programm sollte auf der Konsole kompilierbar und ausführbar sein. Fertige Kompilate sind nicht transparent genug.

**Comment by chede100** [comment]
Ok, habe nun einen neuen Ordner "TDDT-Ohne IDE" hochgeladen, in der das Projekt nicht per IDE aufgebaut wurde.
In der beiliegenden README steht wie ich das Programm kompiliert und ausgeführt habe.
(Hoffentlich sind nun die Bedingungen erfüllt)

**Comment by n2o** [comment]
Wenn ihr doch als Basis Gradle verwendet habt (naja, da kommt ihr nicht drum herum, denn das war eine Anforderung), dann sollte das Projekt mit `gradle build` gebaut und mit `gradle run` ausgeführt werden können...

**Comment by chede100** [comment]
Da haben Sie natürlich Recht. :)
Dann kümmer ich mich Morgen darum.

**Comment by chede100** [comment]
So dritter und hoffentlich letzter Versuch.
Habe den Gradle build ohne IDE Verwendung hochgeladen.
Auf meinem Rechner läuft gradle build + run + selber kompilieren.
(Ordner-Name: TDDT - Ohne IDE mit Gradle)

Habe den Ordner gerade nochmal geupdated jetzt sollte alles reibungslos funktionieren.

**Comment by chede100** [comment]
Kann die Korrektur des Projekts jetzt aufgenommen werden oder fehlt noch etwas?

**Comment by yyazgan** [comment]
Ich der Datei Programm.java befinden sich drei Umlaute. Diese bitte entfernen. Ansonsten ist es eigentlich nicht so sauber, da ihr mehrmals den selben Code in den verschiedenen TDDT-Ordner für verschiedene Build Systeme habt. Es müsste eigentlich auch ohne die speziellen Kopien klappen. Was sagst du dazu @bendisposto ?

**Comment by bendisposto** [comment]
Ich versteh das mit den 3 Versionen auch nicht so ganz, warum macht ihr euch das Leben so schwer? Aber von mir aus ist das ok, es gibt ja eine Version, die mit Gradle auf Travis gebaut wird.

Die Umlaute sollten noch raus, dann ist das denke ich ok.

**Comment by chede100** [comment]
Habe die Umlaute entfernt.

**Comment by chede100** [comment]
Wenn Sie möchten baue ich das Repo so auf wie der Ordner TDDT - Ohne IDE mit Gradle und verknüpfe es mit Travis.
